import { writeFileSync } from "node:fs";
import path from "node:path";

const LLMS_TXT_URL = "https://bun.sh/llms.txt";
const OUTPUT_FILE = path.join(import.meta.dir, "..", "src", "bun-docs.ts");

const DOC_SLUGS: Record<string, string> = {
  autoInstall: "runtime/auto-install",
  bundler: "bundler/index",
  bundlerEsbuild: "bundler/esbuild",
  bunfig: "runtime/bunfig",
  ci: "guides/install/cicd",
  catalogs: "pm/catalogs",
  environmentVariables: "runtime/environment-variables",
  fetch: "runtime/networking/fetch",
  hashing: "runtime/hashing",
  lifecycle: "pm/lifecycle",
  lockfile: "pm/lockfile",
  nodeCompatibility: "runtime/nodejs-compat",
  plugins: "runtime/plugins",
  redis: "runtime/redis",
  securityScanner: "pm/security-scanner-api",
  sqlite: "runtime/sqlite",
  testConfiguration: "test/configuration",
  testRunner: "test/index",
  typescript: "typescript",
  watchMode: "runtime/watch-mode",
  workspaces: "pm/workspaces",
};

const slugToUrl = (slug: string): string => {
  const trimmed = slug.replace(/\/index$/, "");
  return `https://bun.com/docs/${trimmed}`;
};

const collectLlmsUrls = (text: string): Set<string> => {
  const linkPattern = /\(https:\/\/bun\.com\/docs\/([^)\s]+?)(?:\.md)?\)/g;
  const slugs = new Set<string>();
  for (const match of text.matchAll(linkPattern)) {
    if (match[1]) slugs.add(match[1]);
  }
  return slugs;
};

const buildDocFileContents = (entries: Array<[string, string]>): string => {
  const lines = [
    "// Generated by scripts/refresh-bun-docs.ts.",
    "// Do not edit by hand — run `bun run docs:refresh` to update.",
    "",
    "export const BUN_DOCS = {",
  ];
  for (const [key, slug] of entries) {
    lines.push(`  ${key}: "${slugToUrl(slug)}",`);
  }
  lines.push("};", "");
  return lines.join("\n");
};

const main = async (): Promise<void> => {
  const response = await fetch(LLMS_TXT_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${LLMS_TXT_URL}: ${response.status}`);
  }
  const text = await response.text();
  const available = collectLlmsUrls(text);

  const missing: string[] = [];
  for (const [key, slug] of Object.entries(DOC_SLUGS)) {
    if (!available.has(slug)) missing.push(`${key} -> ${slug}`);
  }

  if (missing.length > 0) {
    throw new Error(
      `Bun llms.txt no longer contains these docs:\n${missing.map((entry) => `  - ${entry}`).join("\n")}\nUpdate DOC_SLUGS in scripts/refresh-bun-docs.ts.`,
    );
  }

  const sorted = Object.entries(DOC_SLUGS).sort(([leftKey], [rightKey]) => leftKey.localeCompare(rightKey));
  writeFileSync(OUTPUT_FILE, buildDocFileContents(sorted));
  console.log(`Wrote ${sorted.length} entries to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
};

await main();
