// Generated by scripts/refresh-bun-docs.ts.
// Do not edit by hand — run `bun run docs:refresh` to update.

export const BUN_DOCS = {
  autoInstall: "https://bun.com/docs/runtime/auto-install",
  bundler: "https://bun.com/docs/bundler",
  bundlerEsbuild: "https://bun.com/docs/bundler/esbuild",
  bunfig: "https://bun.com/docs/runtime/bunfig",
  catalogs: "https://bun.com/docs/pm/catalogs",
  ci: "https://bun.com/docs/guides/install/cicd",
  environmentVariables: "https://bun.com/docs/runtime/environment-variables",
  fetch: "https://bun.com/docs/runtime/networking/fetch",
  hashing: "https://bun.com/docs/runtime/hashing",
  lifecycle: "https://bun.com/docs/pm/lifecycle",
  lockfile: "https://bun.com/docs/pm/lockfile",
  nodeCompatibility: "https://bun.com/docs/runtime/nodejs-compat",
  plugins: "https://bun.com/docs/runtime/plugins",
  redis: "https://bun.com/docs/runtime/redis",
  securityScanner: "https://bun.com/docs/pm/security-scanner-api",
  sqlite: "https://bun.com/docs/runtime/sqlite",
  testConfiguration: "https://bun.com/docs/test/configuration",
  testRunner: "https://bun.com/docs/test",
  typescript: "https://bun.com/docs/typescript",
  watchMode: "https://bun.com/docs/runtime/watch-mode",
  workspaces: "https://bun.com/docs/pm/workspaces",
};
