import { BUN_DOCS } from "./constants.js";
import type { CompatEntry } from "./types.js";

export const COMPAT_DB: CompatEntry[] = [
  {
    packageName: "sqlite3",
    severity: "risk",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Native SQLite packages can depend on lifecycle scripts and Node native addon behavior. Bun ships a native SQLite driver.",
    sources: [BUN_DOCS.sqlite, BUN_DOCS.lifecycle],
    lastVerified: "2026-05-12",
    replacement: "bun:sqlite",
    migrationHint: "Evaluate replacing sqlite3 usage with Database from bun:sqlite.",
    requiresTrustedDependency: true,
  },
  {
    packageName: "better-sqlite3",
    severity: "risk",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Native SQLite packages can be sensitive to lifecycle script and Node-API behavior. Bun ships a native SQLite driver.",
    sources: [BUN_DOCS.sqlite, BUN_DOCS.lifecycle, BUN_DOCS.nodeCompatibility],
    lastVerified: "2026-05-12",
    replacement: "bun:sqlite",
    workaround: "If you keep better-sqlite3, verify install and runtime on every target platform.",
    migrationHint: "Evaluate replacing better-sqlite3 usage with Database from bun:sqlite.",
    requiresTrustedDependency: true,
  },
  {
    packageName: "node-sass",
    severity: "risk",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "node-sass commonly relies on native install/build behavior. Bun does not run arbitrary lifecycle scripts by default.",
    sources: [BUN_DOCS.lifecycle],
    lastVerified: "2026-05-12",
    replacement: "sass",
    workaround: "Prefer Dart Sass. If you keep node-sass, explicitly trust it and verify platform installs.",
    migrationHint: "Replace node-sass with sass where possible.",
    requiresTrustedDependency: true,
  },
  {
    packageName: "dotenv",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun automatically loads .env files, so many dotenv usages can be removed.",
    sources: [BUN_DOCS.environmentVariables],
    lastVerified: "2026-05-12",
    replacement: "Bun built-in .env loading",
    migrationHint: "Remove dotenv/config bootstrap code when Bun's automatic .env loading covers the same files.",
  },
  {
    packageName: "node-fetch",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun provides a native fetch implementation through Web APIs.",
    sources: [BUN_DOCS.nodeCompatibility],
    lastVerified: "2026-05-12",
    replacement: "global fetch",
    migrationHint: "Prefer global fetch for new Bun-targeted code.",
  },
  {
    packageName: "cross-fetch",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun provides native Request, Response, Headers, and fetch Web APIs.",
    sources: [BUN_DOCS.nodeCompatibility],
    lastVerified: "2026-05-12",
    replacement: "global fetch",
    migrationHint: "Prefer global fetch when all target runtimes provide it.",
  },
  {
    packageName: "bcrypt",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Bun ships password hashing APIs, which can remove native bcrypt install complexity in some apps.",
    sources: [BUN_DOCS.hashing, BUN_DOCS.lifecycle],
    lastVerified: "2026-05-12",
    replacement: "Bun.password",
    migrationHint: "Evaluate Bun.password for new Bun-only password hashing code.",
    requiresTrustedDependency: true,
  },
  {
    packageName: "ts-node",
    severity: "migration",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun runs TypeScript files directly, so ts-node is often unnecessary after migration.",
    sources: [BUN_DOCS.typescript],
    lastVerified: "2026-05-12",
    replacement: "bun run file.ts",
    migrationHint: "Replace ts-node scripts with bun run or direct bun execution where possible.",
  },
  {
    packageName: "tsx",
    severity: "migration",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun runs TypeScript files directly and has watch/hot modes.",
    sources: [BUN_DOCS.typescript],
    lastVerified: "2026-05-12",
    replacement: "bun run file.ts",
    migrationHint: "Replace tsx scripts with bun run where Bun is the target runtime.",
  },
  {
    packageName: "nodemon",
    severity: "migration",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "high",
    reason: "Bun has built-in watch and hot reload modes for many runtime workflows.",
    sources: ["https://bun.com/docs/runtime/watch-mode"],
    lastVerified: "2026-05-12",
    replacement: "bun --watch or bun --hot",
    migrationHint: "Replace nodemon development scripts with bun --watch or bun --hot when behavior matches.",
  },
  {
    packageName: "jest",
    severity: "migration",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Bun ships a Jest-compatible test runner, but config/setup behavior needs migration review.",
    sources: [BUN_DOCS.testRunner, BUN_DOCS.testConfiguration],
    lastVerified: "2026-05-12",
    replacement: "bun test",
    workaround: "Keep Jest if you rely on unsupported Jest-specific behavior.",
    migrationHint: "Audit jest.config and setup files before replacing test scripts with bun test.",
  },
  {
    packageName: "webpack",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Bun includes a native bundler for many application and library workflows.",
    sources: ["https://bun.com/docs/bundler"],
    lastVerified: "2026-05-12",
    replacement: "bun build",
    migrationHint: "Evaluate bun build for simple library or app bundles before keeping webpack by default.",
  },
  {
    packageName: "esbuild",
    severity: "win",
    affectedRanges: ["*"],
    bunVersions: [">=1.0.0"],
    platforms: ["all"],
    confidence: "medium",
    reason: "Bun includes a native bundler and provides an esbuild migration guide.",
    sources: ["https://bun.com/docs/bundler/esbuild"],
    lastVerified: "2026-05-12",
    replacement: "bun build",
    migrationHint: "Evaluate bun build for build scripts that only need basic esbuild behavior.",
  },
];
